paths:
  data_dir: generative_music/data
  tfrecords_dir: generative_music/data/tfrecords
  midi_data_dir: generative_music/data/midis
  csv_filepath: generative_music/data/dataset.csv
  ckpt_dir: generative_music/data/ckpt
dataset_basenames:
  train: train
  val: validation
  test: test
ratios:
  train_ratio: 0.7
  val_ratio: 0.2
  test_ratio: 0.1
