paths:
  data_dir: generative_music/data
  tfrecords_dir: generative_music/data/tfrecords
  midi_data_dir: generative_music/data/midis
  csv_filepath: generative_music/data/dataset.csv
  ckpt:
    base_dir: generative_music/data/ckpt
    dir_name: 2309301756_test
    number: 19
  tensorboard_dir: generative_music/data/tensorboard
  result_data_dir: generative_music/data/outputs
dataset_basenames:
  train: train
  val: validation
  test: test
ratios:
  train_ratio: 0.8
  val_ratio: 0.2
  test_ratio: 0.0
data_augmentation:
  transpose_amounts: [-3, -2, -1, 0, 1, 2, 3]
  stretch_factors: [0.95, 0.975, 1.0, 1.025, 1.05]
